export default `
  Fake_ (
    locale: String,
    cardVendor: String,
    timeFormat: String,
    dataFormat: String,
    integerFrom: Int,
    integerTo: Int,
    doubleFrom: Int,
    doubleTo: Int,
    arrayOfDigits: Int,
    arrayOfIntegers: Int,
    arrayOfDoubles: Int,
    sentences: Int,
    words: Int,
    arrayOfWords: Int,
    customInt: Int,
    customFloat: Float,
    customString: String,
    customBoolean: Boolean,
    customID: ID
    ): Fake_

  FakeList_ (
    locale: String,
    length: Int, 
    cardVendor: String,
    timeFormat: String,
    dataFormat: String,
    integerFrom: Int,
    integerTo: Int,
    doubleFrom: Int,
    doubleTo: Int,
    arrayOfDigits: Int,
    arrayOfIntegers: Int,
    arrayOfDoubles: Int,
    sentences: Int,
    words: Int,
    arrayOfWords: Int,
    customInt: Int,
    customFloat: Float,
    customString: String,
    customBoolean: Boolean,
    customID: ID
    ): [Fake_]
`;